Repository appuio/component-openshift4-nodes, pull requests merged in 2021-12, with the labels that each got.

#17 Prepare for modulesync
  .sync.yml
  tests/defaults.yml
Labels: change

#19 Configure Pod Limit per node
  class/defaults.yml
  class/openshift4-nodes.yml
  component/common.libsonnet
  component/kubelet.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
Labels: breaking

#20 Fix default matchExpression in kubelet
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
Labels: bug

#21 Create node debug namespace with appropriate annotations
  class/defaults.yml
  class/openshift4-nodes.yml
  component/app.jsonnet
  component/machine-sets.jsonnet
  component/oc-debug-node.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/openshift4-nodes/openshift4-nodes/debug.yaml
Labels: enhancement
