Repository appuio/component-openshift4-nodes, pull requests merged in 2024-06, with the labels that each got.

#82 Support creating ControlPlaneMachineSet
  component/machine-sets.jsonnet
  tests/gcp.yml
  tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-master.yaml
Labels: enhancement

#83 Extend documentation with information on how to manage a `ControlPlaneMachineSet`
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: documentation

#85 Use seperate defaultSpecs for ControlPlaneMachineSet
  class/defaults.yml
  component/machine-sets.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineset-master.yaml
Labels: change
