Repository appuio/component-openshift4-nodes, pull requests merged in 2025-03, with the labels that each got.

#99 Add option to ignore argo sync of `scaleDown.enable` field in the ClusterAutoScalerSpec
  component/autoscaler.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/autoscaling.yml
  tests/golden/autoscaling/openshift4-nodes/apps/openshift4-nodes.yaml
Labels: documentation, enhancement

#100 Use correct api group to ignore cluster autoscaler difference
  component/autoscaler.jsonnet
  tests/golden/autoscaling/openshift4-nodes/apps/openshift4-nodes.yaml
Labels: bug

#102 Remove pipefail bash setting in mc pruning cronjob
  component/scripts/machineconfig_pruning.sh
  tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/capacity/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/defaults/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/gcp/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/machineconfig/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/maxpods/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/pidslimit/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/remove-machineconfigpool/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
Labels: bug, bump:patch

#103 Patch autoscaler args
  class/defaults.yml
  component/autoscaler.jsonnet
  component/espejote-templates/patch-autoscaler-args.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/autoscaling-scheduled.yml
  tests/autoscaling.yml
  tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/autoscaler_inject_args_admission.yaml
  tests/golden/autoscaling/openshift4-nodes/openshift4-nodes/autoscaler_inject_args_jsonnetlibrary.yaml
Labels: enhancement

#104 Support confguring node disruption policies
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  class/openshift4-nodes.yml
  component/espejote-templates/nodedisruptionpolicies-template.jsonnet
  component/espejote-templates/nodedisruptionpolicy-helpers.libsonnet
  component/node-disruption-policies.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/node-disruption-policies/openshift4-nodes/apps/openshift4-nodes.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/.gitkeep.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/01_aggregated_clusterroles.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/10_kubeletconfigs.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/10_nodeconfig.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/debug.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfig_pruning.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-app.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-infra.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/machineconfigpool-storage.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/nodedisruptionpolicies_managedresource.yaml
  tests/golden/node-disruption-policies/openshift4-nodes/openshift4-nodes/nodedisruptionpolicies_rbac.yaml
  tests/node-disruption-policies.yml
Labels: enhancement, bump:minor
